ansible_callback_diy_runner_on_ok_msg: >-
  {{ ansible_callback_diy.result.output.msg | default("") }}
ansible_callback_diy_playbook_on_start_msg: ""
ansible_callback_diy_playbook_on_play_start_msg: ""
ansible_callback_diy_playbook_on_task_start_msg: ""
ansible_callback_diy_playbook_on_stats_msg: ""
#ansible_callback_diy_on_any_msg: >-
#  {% for k, v in ansible_callback_diy.items() %}
#    {{ k }}: {{ v }}
#  {% endfor %}
