- name: Pretty print differences
  vars:
    cols: 3
  debug:
    msg: |
      Missing packages:
      {% for row in extra_packages | sort | batch(cols) %}
      {% for col in row %} {{ "%-20s" | format(col | default('')) }} {% endfor %}

      {% endfor %}

      Extra packages:

#{{ extra_packages | to_nice_yaml }}
