---
- hosts: myself
  gather_facts: false
  vars_prompt:
    - name: comment
      prompt: "enter comment:\n"
      private: false
  post_tasks:
    - set_fact:
        comment: "{{ comment }}"
    - set_fact:
        date_time_comment: "{{ date_time_comment }}"
  roles:
    - dummy

- hosts: myself
  gather_facts: false
  tasks:
    - name: Print some loaded vars
      debug:
        msg: "{{ date_time_comment }}"
