#!/usr/bin/env ansible-playbook
---
- hosts: myself
  gather_facts: false
  vars_prompt:
    - name: comment
      prompt: "enter comment"
      private: false
  roles:
    - dummy
    - saver

- hosts: myself
  gather_facts: false
  tasks:
    - name: Print set facts
      debug:
        msg: |
          {{ date_time_comment }}
          {{ comment }}
