- name: Ask user to save
  pause:
    prompt: Save extra packages? [Y/n]
  register: ans

- name: Save some vars to file
  template:
    src: new-vars.yml.j2
    dest: "{{ playbook_dir }}/group_vars/all/sortme-packages.yml"
  when: ans.user_input | length == 0 or ans.user_input | lower | first == 'y'
