- name: Pretty print differences
  vars:
    cols: 3
  debug:
    msg: |
      {{ title }}
      {% for row in packages_to_print | sort | batch(cols) %}
      {% for col in row %}  {{ "%-25s" | format(col | default('')) }}{% endfor %}

      {% endfor %}
